In [1]:
import numpy as np
import sys
from pathlib import Path

# access the code
sys.path.append((str(Path.cwd() / "src")))
from polytope import Polytope
from plotting_utils import save_plot_and_data_simple, plot_facial_distances_smooth

In [2]:
vertices = np.array([[0, 1, 1, 0],
                    [0, 0, 1, 2]])
vertices = vertices.astype(np.float32)
poly = Polytope(vertices)

y = np.array([0, 1])
grid, dists = poly.vertex_distance_grid(y, step=0.5, epsilon=1e-4, tol=1e-5, parallel=True, num_cores=10)
fig = plot_facial_distances_smooth(grid, dists, y)
save_plot_and_data_simple(fig, vertices, y, name="boolean_hypercube")

Saved plot to results/boolean_hypercube.png and data to results/boolean_hypercube.txt


In [3]:
# 23s 0.1
# 3m 15s 0.05
# 6s 0.1 10 cores
# 41s 0.5 10 cores, eps 1e-5 tol 1e-7
# 41s 0.01 10 cores eps 1e-4 tol 1e-5

In [4]:
# membership oracle
vertices = np.array([[-1, -1, 1, 1],
                     [-1, 1, -1, 1]])
P = Polytope(vertices)
point = np.array([1, 1])
P.membership_oracle(point)
P.support_set_oracle(point)


[[3]]

In [5]:
# Define a simple 2D square polytope
vertices = np.array([[0, 1, 1, 0],
                     [0, 0, 1, 1]])
poly = Polytope(vertices)

# Pick x and y in the polytope
x = np.array([0.2, 0.3])
y = np.array([0.8, 0.7])

# Find a support set for x
support_sets = poly.support_set_oracle(x)
print("Support sets for x:", support_sets)

# Pick the first support set
S_indices = support_sets[0]

# Test gamma_feasible with gamma = 1
feasible, res = poly.gamma_feasible(x, y, S_indices, gamma=0.59999999)
print("Gamma feasible:", feasible)

Support sets for x: [[0, 1, 3], [0, 2, 3], [0, 1, 2, 3]]
Gamma feasible: True


In [6]:
vertices = np.array([
    [1, 2, 3, 4],   # first vertex
    [0, 0, 0, 5],   # second vertex
    [1, 0, 0, 6]    # third vertex
])

In [7]:
_, n = vertices.shape

In [8]:

from itertools import combinations
a = combinations(range(n), 2)

In [9]:
print("vertices")
print(vertices)
for idx in combinations(range(n), 3):
    indices = list(idx)
    print("indices: ", indices)
    print(vertices[:, indices])

vertices
[[1 2 3 4]
 [0 0 0 5]
 [1 0 0 6]]
indices:  [0, 1, 2]
[[1 2 3]
 [0 0 0]
 [1 0 0]]
indices:  [0, 1, 3]
[[1 2 4]
 [0 0 5]
 [1 0 6]]
indices:  [0, 2, 3]
[[1 3 4]
 [0 0 5]
 [1 0 6]]
indices:  [1, 2, 3]
[[2 3 4]
 [0 0 5]
 [0 0 6]]


In [10]:
a = []
b =[]

a.append(b)
a.append(b)
a

[[], []]