In [1]:
import numpy as np
import sys
from pathlib import Path

# access the code
sys.path.append((str(Path.cwd() / "src")))
from polytope import Polytope

In [ ]:
# membership oracle
vertices = np.array([[-1, -1, 1, 1],
                     [-1, 1, -1, 1]])
P = Polytope(vertices)
point = np.array([1, 1])
P.membership_oracle(point)
P.support_set_oracle(point)
point = np.array([1, 1])
direction = np.array([-1, 0])
P.max_step_oracle(point, direction)

2.0000000999971235

In [3]:
vertices = np.array([
    [1, 2, 3, 4],   # first vertex
    [0, 0, 0, 5],   # second vertex
    [1, 0, 0, 6]    # third vertex
])

In [4]:
_, n = vertices.shape

In [5]:

from itertools import combinations
a = combinations(range(n), 2)

In [6]:
print("vertices")
print(vertices)
for idx in combinations(range(n), 3):
    indices = list(idx)
    print("indices: ", indices)
    print(vertices[:, indices])

vertices
[[1 2 3 4]
 [0 0 0 5]
 [1 0 0 6]]
indices:  [0, 1, 2]
[[1 2 3]
 [0 0 0]
 [1 0 0]]
indices:  [0, 1, 3]
[[1 2 4]
 [0 0 5]
 [1 0 6]]
indices:  [0, 2, 3]
[[1 3 4]
 [0 0 5]
 [1 0 6]]
indices:  [1, 2, 3]
[[2 3 4]
 [0 0 5]
 [0 0 6]]


In [7]:
a = []
b =[]

a.append(b)
a.append(b)
a

[[], []]